#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputOption;
use Awssat\Tailwindo\ConsoleHelper;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

(new Application('tailwindo', '1.0.0'))
        
    ->register('tailwindo')
     
    ->addArgument('arg', InputArgument::OPTIONAL, 'a file path/a folder path/Bootstrap CSS classes')

    ->addOption('replace', null, InputOption::VALUE_REQUIRED, 'This will overwrite the original file.', false)

    ->addOption('recursive', 'r', InputOption::VALUE_OPTIONAL, 'This will recurse through all directories under the main directory', false)
     
    ->addOption('extensions', 'e', InputOption::VALUE_REQUIRED, 'This allows for custom extensions', 'php,html')
     
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        // output arguments and options
        $arg = $input->getFirstArgument();

        $arg = trim($arg);

        if (empty($arg)) {
            $output->writeln('<comment>Oops! nothing to convert.</comment>');
            return -1;
        }
        

        $replace = (bool) $input->getOption('replace');

        $is_recursive = (bool) $input->getOption('recursive');

        $acceptedExts = explode(',', $input->getOption('extensions'));
        die(print_r($acceptedExts,true));
        $consoleHelper = new ConsoleHelper($output, $is_recursive, $replace, $acceptedExts);

        //file?
        if (is_file($arg)) {
            return $consoleHelper->fileConvert($arg);
        }

        //folder ?
        if (is_dir($arg)) {
            return $consoleHelper->folderConvert($arg);
        }

        //any html/css classes
        return $consoleHelper->codeConvert($arg);
    })

      ->getApplication()

      ->setDefaultCommand('tailwindo', true)

      ->run();
